### ISSUE TITLE
I want to test in the wild video

### ISSUE THREAD

**Issue by AIM-JS** [zhenhuat/STCFormer#5]
Hi thank you for your research.

I want to test STCFormer model in the wild video.

How can test it? Is there any way to visualization skeleton in the wild video?

**Comment by zhenhuat** [comment]
> Hi thank you for your research.
> 
> I want to test STCFormer model in the wild video.
> 
> How can test it? Is there any way to visualization skeleton in the wild video?


Hi, I employed MHformer's visualization code. 

The wild video can be visualized by referring to MHformer's 'vis.py' [code](https://github.com/Vegetebird/MHFormer/tree/main/demo) and making certain adjustments. Specifically, these adjustments include: (1) referring to MHformer to download the checkpoint for 2D pose estimation, and (2) replacing the network model in 'vis.py' to 'stcformer,' while also adapting the input and output formats of the network. Finally, run the script as following:
`python demo/vis.py --video sample_video.mp4`

I will release this code in the near future, but due to the current shortage of computational resources, it may take a few days before it becomes available.

**Comment by ImHoneyBee** [comment]
Thank you for your answer.

I'll wait for the code to be released. Thanks.

**Comment by AIM-JS** [comment]
Thank you for your answer.

I'll wait for the code to be released. Thanks.

**Comment by zhenhuat** [comment]
> Thank you for your answer.
> 
> I'll wait for the code to be released. Thanks.

Hi, I have modified and released the relevant code, i.e. . /demo folder, you can try it now. See the end of the home page of this project for details on how to use it.

**Comment by AIM-JS** [comment]
Thanks for  your work.

This code works well in the wild video👍
